name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:

          config_timezone: Asia/Kolkata
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_stars: yes
          plugin_achievements: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_code: yes
          plugin_licenses: yes
          plugin_skyline: yes
          config_order: base.header, isocalendar, languages, stars
          token: ${{ secrets.METRICS_TOKEN }}
